# Generated by Django 3.2 on 2022-05-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default=0, max_length=255, verbose_name='주소'),
            preserve_default=False,
        ),
    ]
