# Generated by Django 3.2 on 2022-05-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='경도'),
        ),
    ]
