# Generated by Django 3.2 on 2022-05-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20220513_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name_plural': '1. 카테고리'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '3. 메뉴'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': '2. 음식점'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.maincategory', verbose_name='메인 카테고리'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sub_category',
            field=models.CharField(max_length=100, null=True, verbose_name='서브 카테고리'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
