# Generated by Django 3.2 on 2022-05-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20220513_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='distance',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=5, null=True, verbose_name='거리'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=6, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=6, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='naver_rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True, verbose_name='네이버 별점'),
        ),
    ]
