# Generated by Django 3.2 on 2022-05-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20220513_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='거리'),
        ),
    ]
