# Generated by Django 3.2 on 2022-05-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurant_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_restaurant', to='restaurants.maincategory', verbose_name='메인 카테고리'),
        ),
    ]
