# Generated by Django 3.2 on 2022-05-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20220515_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.URLField(blank=True, null=True, verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='naver_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='네이버 별점'),
        ),
    ]
