version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/docker_swarm/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/files/static
    ports:
      - 80:80
  tasty2b9:
    image: tasty2b9-image:1
    networks:
      - network
    volumes:
      - static-volume:/var/www/tasty2b9/static
    secrets:
      - DJANGO_SECRET_KEY
      - DATABASES_HOST
      - DATABASES_NAME
      - DATABASES_USER
      - DATABASES_PASSWORD
      - DATABASES_PORT
      - NAVER_MAP_CLIENT_ID
      - NAVER_MAP_CLIENT_SECRET
      - X_NAVER_CLIENT_ID
      - X_NAVER_CLIENT_SECRET