# Generated by Django 3.2 on 2022-05-18 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='비밀번호'),
            preserve_default=False,
        ),
    ]
